services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  auth-server:
    build: ./auth-server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      AUTH_DCR_INITIAL_TOKEN: ${AUTH_DCR_INITIAL_TOKEN}
      AUTH_DCR_REQUIRE_INITIAL_TOKEN: ${AUTH_DCR_REQUIRE_INITIAL_TOKEN}
      SERVER_FORWARD_HEADERS: ${SERVER_FORWARD_HEADERS}
      AUTH_ISSUER_URI: ${AUTH_ISSUER_URI}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
    depends_on: [postgres, redis]
    restart: unless-stopped

  resource-server:
    build: ./resource-server
    ports:
      - "8082:8082"
    environment:
      ISSUER_BASE_URI: ${ISSUER_BASE_URI}
      RS_JWK_SET_URI: ${RS_JWK_SET_URI}
    depends_on: [auth-server]
    restart: unless-stopped

  client-app:
    build: ./client-app
    ports:
      - "8081:8081"
    environment:
      # Browser-facing authorize endpoint must be localhost
      OAUTH_AUTH_URI:  http://localhost:8080/oauth2/authorize
      # Back-channel endpoints can use container name
      OAUTH_TOKEN_URI: http://auth-server:8080/oauth2/token
      OAUTH_JWK_URI:   http://auth-server:8080/oauth2/jwks
      OAUTH_USERINFO_URI: http://auth-server:8080/userinfo
      CLIENT_ID: ${CLIENT_ID_MVC}
      CLIENT_SECRET: ${CLIENT_SECRET_MVC}
    depends_on: [auth-server]
    restart: unless-stopped

  oauth-login-redirect-ui:
    build: ./oauth-login-redirect-ui
    ports:
      - "5173:5173"
    restart: unless-stopped

  client-ui:
    build:
      context: ./client-ui
      args:
        VITE_ISSUER: ${VITE_ISSUER}
        VITE_CLIENT_ID: ${VITE_CLIENT_ID}
        VITE_SCOPE: ${VITE_SCOPE}
        VITE_REDIRECT_URI: ${VITE_REDIRECT_URI}
        VITE_RS_BASE: ${VITE_RS_BASE}
    ports:
      - "5174:5174"
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
