server:
  port: 8082
spring:
  security.oauth2.resourceserver.jwt.issuer-uri: ${ISSUER_BASE_URI:http://localhost:8080}
rs.jwk-set-uri: ${RS_JWK_SET_URI:http://auth-server:8080/oauth2/jwks}
cors.allowed-origins: http://localhost:5174
