server:
  port: 9090

spring:
  redis:
    host: localhost
    port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

management:
  endpoints:
    web:
      exposure:
        include: health,info
# authorization-server/src/main/resources/application.yml
auth:
  dcr:
    # set a dev token to require on Authorization: Bearer <token>
    initial-token: "dev-dcr-token-123"
    require-initial-token: true
