server:
  port: 9000

spring:
  # Datasource configuration.  The connection properties can be overridden via
  # environment variables so that the same packaged application may be run in
  # different environments without code changes.  For example, set DB_HOST,
  # DB_PORT, DB_NAME, DB_USERNAME and DB_PASSWORD to point at your production
  # PostgreSQL instance.
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:oauth2db}"
    username: "${DB_USERNAME:postgres}"
    password: "${DB_PASSWORD:1234}"
  flyway:
#    enabled: false
    locations: classpath:db/migration
  redis:
    host: "localhost"
    port: "6379"
auth:
  token:
    access-min: 10
    refresh-days: 15


app:
  issuer: "http://localhost:9000"