# Fixed OAuth2Client/src/main/resources/application.yml
server:
  port: 8091

spring:
  security:
    oauth2:
      client:
        registration:
          client-app:
            client-id: client-app
            client-secret: client-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,orders.read,api.read
            client-name: Test Client App

        provider:
          client-app:
            issuer-uri: http://localhost:9000

# Optional: Enable debug logging
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG