version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: oauth2db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      # Mount the named volume into the correct container directory.  The original
      # configuration omitted the leading slash which caused Docker to create a relative
      # directory instead of using the container's data directory.
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: