server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        registration:
          generic:
            client-id: ${CLIENT_ID:demo-client}
            client-secret: ${CLIENT_SECRET:demo-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/generic"
            scope: openid,profile,email,api.read
        provider:
          generic:
            authorization-uri: ${OAUTH_AUTH_URI:http://localhost:8080/oauth2/authorize}
            token-uri: ${OAUTH_TOKEN_URI:http://auth-server:8080/oauth2/token}
            jwk-set-uri: ${OAUTH_JWK_URI:http://auth-server:8080/oauth2/jwks}
            user-info-uri: ${OAUTH_USERINFO_URI:http://auth-server:8080/userinfo}
